
# -*- coding: utf-8 -*-
"""Workshop_UFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnZjMStRhw9mN2L69d7mU35J4evOevVq
"""

pip install panda

pip install numpy

pip install streamlit

pip install seaborn

pip install ydata_profiling

pip install matplotlib

pip install bnlearn

pip install sweetviz

pip install pandas

from IPython.core import prefilter
# install all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as prefilter
import seaborn as sns
import sweetviz as sv
import ydata_profiling as pp
import bnlearn as bn

from google.colab import files

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Create a sample DataFrame (replace this with your actual DataFrame)
df = pd.DataFrame({
    'col1': [1, 2, 3, 4, 5],
    'col2': ['A', 'B', 'A', 'C', 'B']
})

# Generate the sweetviz report
report = sv.analyze(df)

# Show the HTML report
report.show_html("sweetviz.html")

df=pd.read_csv("Pr_Ag1.csv")



df.head()

df.tail()

df.info()

report = sv.analyze(df)

df.describe()

df.sum(numeric_only=True)

df.duplicated().sum()

df.isnull().sum()

df.to_csv("Pr_Ag1.csv")

"""ydata_profiling"""

profile = pp.ProfileReport(df, title = "Data Profile Report", explorative = True)

profile.to_file("data_exproration_ydata.html")

!pip install -q scikit-learn pandas matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_curve, auc
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import learning_curve

print(df.head())

print(df.tail())

print("\nDataset Information:")
print(df.info())

"""# Statistical summary"""

print("\nStatistical Summary:")
print(df.describe())

"""# Missing values"""

print("\nMissing Values:")
print(df.isnull().sum())

plt.figure(figsize=(10, 6))
sns.heatmap(df.isnull(), cmap='viridis', cbar=False)

plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True),
            annot=True,
            cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

"""Specify the Class Variable"""

target = "DubityMet"

"""# feature and Target"""

x = df.drop(columns=[target])
y = df[target]

x = pd.get_dummies(x)

x_train, x_test, Y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
    )

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor()
knn.fit(x_train, Y_train)

"""Run the Modek"""

y_pred = knn.predict(x_test)

from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R2): {r2}")

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Convert continuous 'DubityMet' into a binary classification target
# Assuming 'DubityMet' > 0 means 'rain' (1) and 'DubityMet' == 0 means 'no rain' (0)
y_classification = (y > 0).astype(int)

# Split data with the new classification target
x_train_cls, x_test_cls, y_train_cls, y_test_cls = train_test_split(
    x,
    y_classification,
    test_size=0.2,
    random_state=42
)

# Scale the features (using the same scaler as before, or re-fit if necessary for this split)
# Re-initializing scaler to ensure it's fit on the classification training data if not explicitly done before
scaler_cls = StandardScaler()
x_train_cls_scaled = scaler_cls.fit_transform(x_train_cls)
x_test_cls_scaled = scaler_cls.transform(x_test_cls)

# Initialize and train a Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(x_train_cls_scaled, y_train_cls)

# Make predictions on the test set
y_pred_cls = rf_classifier.predict(x_test_cls_scaled)

# Evaluate the classifier
print("\nRandom Forest Classifier Performance:")
print(f"Accuracy: {accuracy_score(y_test_cls, y_pred_cls):.4f}")
print(f"Precision: {precision_score(y_test_cls, y_pred_cls, zero_division=0):.4f}")
print(f"Recall: {recall_score(y_test_cls, y_pred_cls, zero_division=0):.4f}")
print(f"F1 Score: {f1_score(y_test_cls, y_pred_cls, zero_division=0):.4f}")

print("\nClassification Report:")
print(classification_report(y_test_cls, y_pred_cls, zero_division=0))

# Plotting the Confusion Matrix
cm = confusion_matrix(y_test_cls, y_pred_cls)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['No Rain (0)', 'Rain (1)'],
            yticklabels=['No Rain (0)', 'Rain (1)'])
plt.title('Confusion Matrix - Random Forest Classifier')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

train_size, train

from sklearn.model_selection import learning_curve

# Calculate learning curve scores
train_sizes, train_scores, test_scores = learning_curve(
    rf_classifier, x_train_cls_scaled, y_train_cls, cv=5, n_jobs=-1,
    train_sizes=np.linspace(0.1, 1.0, 10), scoring='accuracy'
)

# Calculate mean and standard deviation for train and test scores
train_scores_mean = np.mean(train_scores, axis=1)
train_scores_std = np.std(train_scores, axis=1)
test_scores_mean = np.mean(test_scores, axis=1)
test_scores_std = np.std(test_scores, axis=1)

# Plot the learning curve
plt.figure(figsize=(10, 7))
plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                 train_scores_mean + train_scores_std, alpha=0.1, color="r")
plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                 test_scores_mean + test_scores_std, alpha=0.1, color="g")
plt.plot(train_sizes, train_scores_mean, 'o-', color="r",
         label="Training score")
plt.plot(train_sizes, test_scores_mean, 'o-', color="g",
         label="Cross-validation score")
plt.title("Learning Curve - Random Forest Classifier")
plt.xlabel("Training Examples")
plt.ylabel("Score")
plt.legend(loc="best")
plt.grid(True)
plt.show()

"""### Hyperparameter Tuning with GridSearchCV

To improve the model's performance and potentially reduce overfitting, we can perform hyperparameter tuning using `GridSearchCV`. This method exhaustively searches over specified parameter values for an estimator and selects the best combination.
"""

from sklearn.model_selection import GridSearchCV

# Define the parameter grid to search
param_grid = {
    'n_estimators': [50, 100, 200],  # Number of trees in the forest
    'max_depth': [None, 10, 20, 30], # Maximum number of levels in tree
    'min_samples_split': [2, 5, 10], # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4],   # Minimum number of samples required to be at a leaf node
    'max_features': ['sqrt', 'log2', None] # Number of features to consider when looking for the best split
}

# Initialize GridSearchCV
# We'll use the same RandomForestClassifier instance and classification data
grid_search = GridSearchCV(estimator=rf_classifier,
                           param_grid=param_grid,
                           cv=3,  # Using 3-fold cross-validation for speed, can increase for more robust results
                           n_jobs=-1, # Use all available cores
                           verbose=2, # Verbose output
                           scoring='accuracy') # Metric to optimize

# Fit GridSearchCV to the training data
grid_search.fit(x_train_cls_scaled, y_train_cls)

# Print the best parameters and best score
print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best cross-validation accuracy: {grid_search.best_score_:.4f}")

# Get the best model
best_rf_classifier = grid_search.best_estimator_

# Evaluate the best model on the test set
y_pred_best = best_rf_classifier.predict(x_test_cls_scaled)

print("\nPerformance of the best Random Forest Classifier (after tuning):")
print(f"Accuracy: {accuracy_score(y_test_cls, y_pred_best):.4f}")
print(f"Precision: {precision_score(y_test_cls, y_pred_best, zero_division=0):.4f}")
print(f"Recall: {recall_score(y_test_cls, y_pred_best, zero_division=0):.4f}")
print(f"F1 Score: {f1_score(y_test_cls, y_pred_best, zero_division=0):.4f}")

print("\nClassification Report (tuned model):")
print(classification_report(y_test_cls, y_pred_best, zero_division=0))
